### PR TITLE
Use Aria2

### PR DESCRIPTION
**Pull request by RealAkito**
Signed-off-by: Akito Mizukito <peak@echln.net>

### CODE REVIEW

**Comment by RealAkito** [comment]
@RealAkito Do not merge yet

**Comment by RealAkito** [comment]
You can surely merge now :) 

Please squash

**Comment by RealAkito** [comment]
Hmm will fix more stuff don't merge yet lmao

**Comment by RealAkito** [comment]
Totally fixed

**Comment by erfanoabdi** [comment]
Thanks for your contribution

**Comment by iamsaalim** [comment]
thanks

**Pull request merged**
