### PR TITLE
MIUI9: Fix Mi Account & Themes

### PR DESCRIPTION
**Pull request by caneray**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
wew, are you sure all these are needed? 
like display hals are really needed?

**Comment by caneray** [comment]
It does not cause any problems in stability. Fix was tried by me.

**Comment by erfanoabdi** [comment]
ok you need to add more thing to this patch 
file_contexts like this : https://github.com/erfanoabdi/ErfanGSIs/blob/master/roms/9/OxygenOS/file_contexts
and add it to make.sh

**Comment by caneray** [comment]
I will send new pull request wait bro.

**Comment by erfanoabdi** [comment]
use u:object_r:hal_allocator_default_exec:s0 for hals and u:object_r:update_engine_exec:s0 for bins

**Pull request closed without merging**
