### PR TITLE
OxygenOS: Correct op6 notch path

### PR DESCRIPTION
**Pull request by Nick-infinity**
Signed-off-by: Nick-Infinity <nikhilg.me@gmail.com>

### CODE REVIEW

**Comment by erfanoabdi** [comment]
0s length is not same as the notch path

**Comment by Nick-infinity** [comment]
It matters? Actually i have been using same number of zeroes on my device and it works fine.Let me know how i can fix that, i will create a new pr

**Comment by erfanoabdi** [comment]
yeah matters, just rebase this commit with new edits and plz just add your notch path in a new line and keep my old path

**Comment by Nick-infinity** [comment]
i mean how do i calculate the zeroes for it.

**Comment by erfanoabdi** [comment]
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by erfanoabdi** [comment]
merged

**Pull request closed without merging**
